### ISSUE TITLE
WebpackBundleLookupError thrown when webpack entry name is different from bundle name in Django template

### ISSUE THREAD

**Issue by RonyLevAri** [ezhome/django-webpack-loader#117]
Hi and thank you first for this Django-React integration solution.  

I would like to suggest adding to the "Template" section in the documentation, an explicit clarification that the bundle name to render in `{% render_bundle 'name' 'js' %}` is referring to the webpack entry name in the webpack configuration file and not some bundle file name prefix. 

For the following webpack entry configuration:
```javascript
module.exports = {
    entry: {
        index: ['whatwg-fetch', './src/index.js']
    },
    output: {
        path: path.resolve('dist'),
        filename: '[name].bundle.js'
    },...
```
I got he following webpack-stats:
```javascript
{"status":"done","chunks":{"index":[{"name":"index.bundle.js","path":"/[path]/ui/dist/index.bundle.js"}]}}
```
And got a  WebpackBundleLookupError because I was using `{% render_bundle 'index.bundle' 'js' %}` in my template. The error itself did not expose any explicit lookup logic problem stemming from the parameters: 

```javascript
assets :	{'chunks': {'index': [{'name': 'index.bundle.js',
                       'path': '[path]/ui/dist/index.bundle.js'},
                      ]},'status': 'done'}
bundle_name : 'index.bundle'
```

So I needed to look into the source code, using some old school debugging, to realize that what is referred to as "bundle_name" actually refers to the webpack configuration entry name ("index").

It might be obvious to most people but it wasn't for me, and i just wanted to post this issue and its resolution in case someone else could benefit from it.

**Comment by Lokgic** [comment]
THANK YOU! I spent hours trying to debug this.

**Comment by owais** [comment]
Thanks for bring this up. Would gladly accept a PR that patches the docs. Thanks

**Comment by RamazanDemirci** [comment]
Problem : 
### WebpackBundleLookupError at /
Cannot resolve bundle main.

Request Method: GET
Request URL: http://127.0.0.1:8000/
Django Version: 3.0.3
Exception Type: WebpackBundleLookupError
Exception Value: Cannot resolve bundle main.

### webpack-stats.json
```
{
   "status":"done",
   "publicPath":"http://localhost:8080/frontend/dist/",
   "chunks":{
      "app":[
         {
            "name":"app.bundle.js",
            "publicPath":"http://localhost:8080/frontend/dist/app.bundle.js",
            "path":"[_full_path_]\\frontend\\dist\\app.bundle.js"
         }
      ]
   }
}
```

### index.html   [Template]
```
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">

<head>
....
</head>
<body>
    <div id="app"></div>
    {% render_bundle 'main' %}
...
</body>
```


I cant share all files content maybe your problem different place in your code.
Problem stemming from x this line. because of y. something don't comply with other. i spent much time for research. i tried very different things.
I noticed randomly this solution with a question in stackoverflow.

My Solution : 

in webpack-stats.json file; under "chunks"  ; you see "app" tag. get the mistaken line {% render_bundle 'main' %} and change **main** to **app**
your code should be as following;
{% render_bundle 'app' %}

i dont know very well about webpack and django-webpack-loader but i I inferenced that  
-  render_bundle from webpack_loader ; load your assets(js, css, images vb.) which defined in webpack-stats.json. 
- this problem stemming from 'main' did not exist in webpack-stats.json thus webpack_loader can not resolve this word.

this resolved my problem. i hope this post benefit someone
