### ISSUE TITLE
how to serve the bundle files in DEBUG in remote host?

### ISSUE THREAD

**Issue by pcompassion** [ezhome/django-webpack-loader#120]
I'm building (run webpack) on local machine and collectstatic.  

I do rsync the static directory to a production server after that.

I sometimes need to run server with DEBUG=True on the production server.

Webpack generated files are requested due to `render_bundle` but the bundles are not served correctly because they are in the `STATIC_ROOT` directory only and not found with static_finders.

What are the recommended way of serving the bundles in debug mode in remote host?

**Comment by owais** [comment]
It should work with proper configuration. It would be helpful to share the config. May be share an example django project on github

**Comment by littlehome-eugene** [comment]
I can instead point to the relevant code in django why this doesn't work.


`django.contrib.staticfiles.views.serve` tries to matched the path using finders.
```

 def get_finders():
     for finder_path in settings.STATICFILES_FINDERS:
         yield get_finder(finder_path)

```

And as noted in django docs (https://docs.djangoproject.com/en/1.11/ref/settings/#staticfiles-finders)

STATICFiLES_FINDERS are defaulted to 
```
[
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
```

The two finders don't look at the `STATIC_ROOT` (which is collected by collect_static).  
They only look at the source directories..

**Comment by owais** [comment]
I suggest to use `publicPath` in your webpack config when you build bundles for remote server. `publicPath` in your webpack config should be pointed to the static files URL of your remote server meaning if you remote server's static files can be retrieved from the url `https://my-remote-server.com/static/`, then you `publicPath` in webpack should be `https://my-remote-server.com/static/` so that `render_bundle` creates the final URL by concatenating the `publicPath` and the bundle name. Thus, if you bundle is named `main.123456.js` and is stored at the root of your static files dir, `render_bundle` will generate a url that looks like `https://my-remote-server.com/static/main.123456.js`.

I suggest to try and figure out what the full URL of your bundles is. If you rsynched a bundle named `main.123.js` to the server, try to access it directly from browser by using the full static URL configured in django. If it turns out to be `https://my-server.com/static/bundles/main.123.js`, then setting `https://my-server.com/static/bundles/` as the `publicPath` in your webpack should make it work.

**Comment by littlehome-eugene** [comment]
My production server is located at `http://my-remote-server.com`.
(behind nginx/uwsgi)

My test server (on the production machine) is located at `http://my-remote-server.com:10001` . 
(on runserver)

I'm not sure your `publicPath` approach is still applicable when they have different path (port)

**Comment by owais** [comment]
You need to set pulicPath conditionally based on the ENV or have different webpack configs that inherit from a common one. You can pass an environment variable to influence public path like

```bash
ENV=production webpack --config path/to/config
```
 
Then inside the webpack config file, check the value of ENV and set publicPath accordingly
