### ISSUE TITLE
Is there a way to get bundle.js from assets without moving it to static files folder.

### ISSUE THREAD

**Issue by untitledboy** [ezhome/django-webpack-loader#124]
Here's my settings.py file.
```
INSTALLED_APPS = (
 ...
 'webpack_loader',
)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = '/media/static/'

STATICFILES_DIRS = (
    #This lets Django's collectstatic store our bundles
    os.path.join(BASE_DIR, 'assets'),
)

WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}
```
I get an error
>GET http://mysite.com/media/static/bundles/main-0652d463d4d7a46e6141.js 404 (Not Found)

After running
>python manage.py collectstatic

The problem was solved.

But now I need to run **collectstatic** every time after making changes in bundle.

How does it work in [this example](https://github.com/ezhome/django-webpack-loader/tree/master/examples/simple) without collectstatic command?

**Comment by mozartilize** [comment]
maybe you need to set `output.publicPath: 'media/static/bundles/'` in webpack.config.js, then rebuild

**Comment by raprasad** [comment]
For local development, I did this as a workaround:


#### (1) Update `settings.py` (in my case case settings/local_settings.py)

```python
# added to settings
TEST_DIRECT_STATIC = os.path.join(BASE_DIR, 'assets')
```

- This is the same directory specified in your `STATICFILES_DIRS`

---

#### (2)  Update the ```urls.py``` file

Note that `TEST_DIRECT_STATIC` is being used instead of `STATIC_ROOT`

  ```python
  # (1) Add these lines at the top:
  #
  from django.conf import settings
  from django.conf.urls.static import static

  # (2) Add the '+ static(...) section 
  #
  urlpatterns = [
      url(r'^admin/', admin.site.urls),

      # ... your other urls ...

  ] + static(settings.STATIC_URL,
                  document_root=settings.TEST_DIRECT_STATIC)
  ```

- This should work for a basic setup where all of your static assets are in `os.path.join(BASE_DIR, 'assets')`
- The static url info is from https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-static-files-during-development
(using this on Django 1.11.4)

**Comment by owais** [comment]
I think adding the directory that contains the generated bundles to the staticfiles dirs will enable this in development. You might have to fiddle with some paths to make sure everything adds up. e.g, `publicPath` in webpack or may be remove it entirely in development.
