### ISSUE TITLE
Is it make sense to read the `STATS_FILE ` from url instead filesystem ?

### ISSUE THREAD

**Issue by jubel-han** [ezhome/django-webpack-loader#91]
The `STATS_FILE ` file is reading from filesystem path, is it possible relative with `BUNDLE_DIR_NAME` or `STATIC_ROOT` so that support for reading from URL ?

For the production practice that we are building webpack on one deployment server, together with collectstatic actions, all of asserts will collected to s3 bucket as the CDN origin source.
but we have multiple app servers (django) which need read the `STATS_FILES` from filesystem, so we have to upload the status files to every servers, it is ugly for me ...
I think this construction should be normally, or is there more better suggestion or practices ?

**Comment by owais** [comment]
> which need read the STATS_FILES from filesystem, so we have to upload the status files to every servers, it is ugly for me ..

I personally don't think it's so bad. After all, you are already pushing all your python code, migrations, configuration, etc to all servers anyway by pulling from a repo, scp'ing a zip or creating a docker image. I think the stats file should be treated as part of the build (it is) and delivered with the build instead of as a static file. There is no reason to put this file on a CDN with other static assets as it's purpose is not to be publicly available for clients but be available to your server code as part of the build.

However, the topic has come up before and if you'd really like to load it from a URL at runtime instead of bundling it with build at build time, I've suggested a way to achieve this in an existing PR [0]. The idea is to let users override the stats loading code completely so each user can load code from anywhere they (CDN, Database, Redis, Filesystem, etc) want in just a few lines of code. Such a custom loading can also be shipped as a 3rd party app like `webpack-loader-remote`.

PRs are always welcome.


[0] https://github.com/owais/django-webpack-loader/pull/83
